name: Execute request.js daily

on:
  push:  # Triggers on a push event to the repository
    branches:
      - main  # Specify the branch to listen for pushes (e.g., 'main')
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  run-request-script:
    runs-on: windows-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up 32-bit Node.js environment
    - name: Set up 32-bit Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.17'
        architecture: 'x86' # Specify 32-bit architecture


    # Step 3: Navigate to the script's directory and install dependencies
    - name: Install dependencies
      run: |
        npm install

    # Step 4: Execute the script
    - name: Run request.js
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        API_KEY: ${{ secrets.API_KEY }}
        RPC_URL: ${{ secrets.RPC_URL }}
      run: |
        node request.js
